name: matrix_accounts
description: Offline-first multi-company accounts & inventory app
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.0
  go_router: ^17.0.1

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  path_provider: ^2.1.0
  excel: ^4.0.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7
  file_picker: ^10.0.0
  pdf: ^3.10.0
  printing: ^5.11.0
  share_plus: ^12.0.1
  path: ^1.8.3
  package_info_plus: ^9.0.0
  screenshot: ^3.0.0
  local_auth: ^3.0.0
  crypto: ^3.0.3
  http: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/excel_templates/
